name: Record and Deploy

on:
  workflow_dispatch:
    inputs:
      score:
        description: '気分のスコア (0-10)'
        required: true
        type: choice
        options:
          - '0'
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'
          - '6'
          - '7'
          - '8'
          - '9'
          - '10'
      note:
        description: '任意のメモ'
        required: false
        type: string
      date:
        description: '記録日時 (YYYY-MM-DDTHH:MM:SS+09:00形式, 未入力なら現在時刻)'
        required: false
        type: string

permissions:
  contents: write
  pages: write
  id-token: write

env:
  INPUT_DATE: ${{ github.event.inputs.date }}
  INPUT_SCORE: ${{ github.event.inputs.score }}
  INPUT_NOTE: ${{ github.event.inputs.note }}
  LIST_FILE: public/data/history-list.jsonl

jobs:
  record:
    name: Record Mood History
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Parse and Record Inputs
        run: |
          import os, sys, json
          from datetime import datetime, timezone, timedelta
          from pathlib import Path

          # 入力値取得
          input_date = os.environ.get('INPUT_DATE')
          input_score = os.environ.get('INPUT_SCORE')
          input_note = os.environ.get('INPUT_NOTE')
          list_file = os.environ.get('LIST_FILE')

          # 日付パース: 未入力なら現在時刻（JST)，厳格にISO 8601チェック
          if not input_date:
              now = datetime.now(timezone(timedelta(hours=9)))
              input_date = now.isoformat()
          try:
              dt = datetime.fromisoformat(input_date)
          except Exception:
              print(f'[ERROR] date は ISO 8601 形式で入力してください: {input_date}', file=sys.stderr)
              sys.exit(1)

          # 年月日を切り出す
          input_yearmonth = input_date[:4] + '-' + input_date[5:7]
          history_file = f'public/data/history/{input_yearmonth}.jsonl'

          # LIST_FILE の更新
          Path('public/data').mkdir(parents=True, exist_ok=True)
          Path(list_file).touch(exist_ok=True)
          found = False
          with open(list_file, encoding='utf-8') as f:
              for line in f:
                  try:
                      obj = json.loads(line)
                      if obj.get('date') == input_yearmonth:
                          found = True
                          break
                  except Exception:
                      continue
          if not found:
              with open(list_file, 'a', encoding='utf-8') as f:
                  f.write(json.dumps({'date': input_yearmonth}, ensure_ascii=False, separators=(',', ':')) + '\n')

          # HISTORY_FILE の更新
          Path('public/data/history').mkdir(parents=True, exist_ok=True)
          data = {'date': input_date, 'score': int(input_score)}
          if input_note:
              data['note'] = input_note
          with open(history_file, 'a', encoding='utf-8') as f:
              f.write(json.dumps(data, ensure_ascii=False, separators=(',', ':')) + '\n')

          # GITHUB_ENV への出力（他stepで必要なら）
          with open(os.environ['GITHUB_ENV'], 'a', encoding='utf-8') as f:
              f.write(f'INPUT_YEARMONTH={input_yearmonth}\n')
              f.write(f'HISTORY_FILE={history_file}\n')
        env:
          INPUT_DATE: ${{ env.INPUT_DATE }}
          INPUT_SCORE: ${{ env.INPUT_SCORE }}
          INPUT_NOTE: ${{ env.INPUT_NOTE }}
          LIST_FILE: ${{ env.LIST_FILE }}
        shell: python

      - name: Amend Commit and Push Changes
        uses: ryancyq/github-signed-commit@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            public/data/history-list.jsonl
            public/data/history/*.jsonl
          commit-message: |
            ${{ github.event.inputs.date }} / Score [${{ github.event.inputs.score }}]

            ${{ github.event.inputs.note }}

  deploy:
    needs: record
    uses: ./.github/workflows/deploy.yml
    with:
      ref: ${{ github.ref }}
